### ISSUE TITLE
Notion inline is here!

### ISSUE THREAD

**Issue by Shubodh** [evertheylen/notion-inline-math#4]
The Notion inline feature is here! Congratulations and thank you @evertheylen, you and the Notion Hacks community has successfully put pressure on Notion to roll out the Notion inline feature. 
I think it is a good idea to proudly add in README that your repo is obsolete now. Never had anyone been happy because their repo has become obsolete. :smile:

**Comment by evertheylen** [comment]
Haha thanks :)
